redis: &redis
  adapter: redis
  url: redis://redistogo:011f3ea2d5060d4b361a0d29fd297e3d@scat.redistogo.com:10473/

production: *redis

development:
  adapter: async

test:
  adapter: async

# development:
#   adapter: redis
#   url: redis://127.0.0.1:6379/0
#
# test:
#   adapter: redis
#   url: redis://127.0.0.1:6379/0
#
# production:
#   adapter: redis
#   url: redis://127.0.0.1:6379/0
#   channel_prefix: help_van_production
