default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *defaults
  database: helpvan

test:
  <<: *defaults
  database: helpvan

production:
  <<: *defaults
  database: helpvan
  username: ahyoungin
